name: UI Automation Testing
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        # api-level: 29
        api-level: 33
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace
